"""
Localization strings for the application.
"""

LANGUAGES = {
    "en": {
        "title": "SimpleRef (GPU Accelerated)",
        "file": "File",
        "open_image": "Add Images",
        "save_board": "Save Board",
        "load_board": "Load Board",
        "clear_board": "Clear Board",
        "settings": "Settings",
        "language": "Language",
        "always_on_top": "Always on Top",
        "help": "Help",
        "about": "About",
        "exit": "Exit",
        "about_text": "SimpleRef (GPU)\nA GPU-accelerated reference image viewer.\n\nControls:\n- Right Click: Menu\n- Left Drag: Move Image\n- Middle Drag / Space + Left Drag: Pan Canvas\n- Wheel: Zoom Canvas\n- Delete: Remove Image\n- G: Group Selected Images",
        "error": "Error",
        "save_error": "Failed to save file: {}",
        "load_error": "Failed to load file: {}",
        "appearance": "Appearance",
        "bg_color": "Background Color",
        "grid_color": "Grid Color",
        "grid_size": "Grid Size",
        "show_grid": "Show Grid",
        "pick_color": "Pick Color",
        "ok": "OK",
        "cancel": "Cancel",
        "preferences": "Preferences",
        "reset_defaults": "Reset Defaults",
        "organize_items": "Smart Organize",
        "export_image": "Export as Image",
        "export_to_clipboard": "Copy to Clipboard",
        "warning": "Warning",
        "no_images_to_export": "No images on the canvas to export.",
        "success": "Success",
        "export_success": "Board exported successfully to:\n{}",
        "export_error": "Failed to export image.",
        "clipboard_success": "Image copied to clipboard.",
        "clipboard_error": "Failed to copy image to clipboard.",
        "reset_board": "Reset Board Size",
        "auto_reset_board": "Auto Reset Board",
        "auto_reset_interval": "Auto Reset Interval (minutes)",
        "board_settings": "Board",
        "edit": "Edit",
        "undo": "Undo",
        "redo": "Redo",
        "layer": "Layer",
        "bring_forward": "Bring Forward",
        "send_backward": "Send Backward",
        "bring_to_front": "Bring to Front",
        "send_to_back": "Send to Back",
        # 组功能 / Group feature
        "group": "Group",
        "group_selected": "Group Selected",
        "ungroup": "Ungroup",
        "group_settings": "Group Settings",
        "group_name": "Group Name",
        "group_color": "Color",
        "font_size": "Font Size",
        "opacity": "Opacity",
        # 智能对齐 / Smart Guides
        "smart_guides": "Smart Guides",
        "smart_guides_on": "✓ Smart Guides (On)",
        "smart_guides_off": "Smart Guides (Off)",
        # Win11 窗口特效 / Win11 window effects
        "win11_effects": "Win11 Effects",
        "window_opacity": "Background Opacity",
        "acrylic_effect": "Acrylic Background",
        "acrylic_tip": "Requires Windows 10 1809+. Restart may be needed.",
        "effect_applied": "Win11 effect applied.",
        "effect_removed": "Win11 effect removed.",
        "effect_not_supported": "Current system does not support this effect.",
        # 画板主题 / Canvas theme
        "canvas_theme": "Canvas Theme",
        "theme_dot_grid": "Dot Grid",
        "theme_ue5_blueprint": "UE5 Blueprint",
        "ue5_bg_color": "Blueprint Background",
        "ue5_small_grid_color": "Small Grid Color",
        "ue5_large_grid_color": "Large Grid Color",
        "ue5_large_grid_multiplier": "Large Grid Interval",
        "ue5_small_line_width": "Small Grid Line Width",
        "ue5_large_line_width": "Large Grid Line Width",
        "ue5_small_line_alpha": "Small Grid Opacity",
        "ue5_large_line_alpha": "Large Grid Opacity",
        "dot_size": "Dot Size",
        # 色深模式 / Color Depth Mode
        "color_depth": "Color Depth",
        "color_depth_mode": "Color Depth Mode",
        "color_depth_auto": "Auto (Adaptive)",
        "color_depth_8bit": "8bit (Standard)",
        "color_depth_10bit": "10bit (High Color)",
        "color_depth_16bit": "16bit (Maximum)",
        "color_depth_tip": "Auto mode: high-bit images render at high bit depth, low-bit images at 8bit. Restart required after change.",
        "color_depth_restart": "Color depth mode changed. Please restart the application for it to take effect.",
        # 汉堡菜单 / Hamburger menu
        "menu_tooltip": "Menu"
    },
    "zh_cn": {
        "title": "SimpleRef (GPU 加速版)",
        "file": "文件",
        "open_image": "添加图片",
        "save_board": "保存看板",
        "load_board": "读取看板",
        "clear_board": "清空看板",
        "settings": "设置",
        "language": "语言",
        "always_on_top": "始终置顶",
        "help": "帮助",
        "about": "关于",
        "exit": "退出",
        "about_text": "SimpleRef (GPU)\n一个基于 GPU 加速的参考图查看器。\n\n操作说明:\n- 右键: 菜单\n- 左键拖拽: 移动图片\n- 中键拖拽 / 空格+左键: 移动画布\n- 滚轮: 缩放画布\n- Delete: 删除图片\n- G: 打组选中图片",
        "error": "错误",
        "save_error": "保存文件失败: {}",
        "load_error": "读取文件失败: {}",
        "appearance": "外观",
        "bg_color": "背景颜色",
        "grid_color": "网格颜色",
        "grid_size": "网格大小",
        "show_grid": "显示网格",
        "pick_color": "选择颜色",
        "ok": "确定",
        "cancel": "取消",
        "preferences": "首选项",
        "reset_defaults": "恢复默认",
        "organize_items": "智能整理",
        "export_image": "导出为图片",
        "export_to_clipboard": "复制到剪贴板",
        "warning": "警告",
        "no_images_to_export": "画布上没有可导出的图片。",
        "success": "成功",
        "export_success": "画布已成功导出至:\n{}",
        "export_error": "导出图片失败。",
        "clipboard_success": "图片已复制到剪贴板。",
        "clipboard_error": "复制图片到剪贴板失败。",
        "reset_board": "重置画板大小",
        "auto_reset_board": "自动重置画板",
        "auto_reset_interval": "自动重置间隔（分钟）",
        "board_settings": "画板",
        "edit": "编辑",
        "undo": "撤销",
        "redo": "重做",
        "layer": "层级",
        "bring_forward": "上移一层",
        "send_backward": "下移一层",
        "bring_to_front": "移至顶层",
        "send_to_back": "移至底层",
        # 组功能 / Group feature
        "group": "组",
        "group_selected": "打组",
        "ungroup": "解散组",
        "group_settings": "组设置",
        "group_name": "组名称",
        "group_color": "颜色",
        "font_size": "字体大小",
        "opacity": "透明度",
        # 智能对齐 / Smart Guides
        "smart_guides": "智能对齐",
        "smart_guides_on": "✓ 智能对齐（已开启）",
        "smart_guides_off": "智能对齐（已关闭）",
        # Win11 窗口特效 / Win11 window effects
        "win11_effects": "Win11 特效",
        "window_opacity": "背景不透明度",
        "acrylic_effect": "亚克力背景",
        "acrylic_tip": "需要 Windows 10 1809 及以上版本。",
        "effect_applied": "Win11 特效已应用。",
        "effect_removed": "Win11 特效已移除。",
        "effect_not_supported": "当前系统不支持此特效。",
        # 画板主题 / Canvas theme
        "canvas_theme": "画板主题",
        "theme_dot_grid": "点阵网格",
        "theme_ue5_blueprint": "UE5 蓝图",
        "ue5_bg_color": "蓝图背景色",
        "ue5_small_grid_color": "小网格颜色",
        "ue5_large_grid_color": "大网格颜色",
        "ue5_large_grid_multiplier": "大网格间隔",
        "ue5_small_line_width": "小网格线宽",
        "ue5_large_line_width": "大网格线宽",
        "ue5_small_line_alpha": "小网格透明度",
        "ue5_large_line_alpha": "大网格透明度",
        "dot_size": "点大小",
        # 色深模式 / Color Depth Mode
        "color_depth": "色深",
        "color_depth_mode": "色深模式",
        "color_depth_auto": "自适应",
        "color_depth_8bit": "8bit（标准色深）",
        "color_depth_10bit": "10bit（高色深）",
        "color_depth_16bit": "16bit（最高精度）",
        "color_depth_tip": "自适应模式：高位深图像以高位深渲染，低位深图像以8bit渲染。切换后需重启应用。",
        "color_depth_restart": "色深模式已更改，请重启应用程序以生效。",
        # 汉堡菜单 / Hamburger menu
        "menu_tooltip": "菜单"
    }
}
